<option value="glass" data-icon="fa-glass" data-subtext="glass"></option>
<option value="music" data-icon="fa-music" data-subtext="music"></option>
<option value="search" data-icon="fa-search" data-subtext="search"></option>
<option value="envelope-o" data-icon="fa-envelope-o" data-subtext="envelope-o"></option>
<option value="heart" data-icon="fa-heart" data-subtext="heart"></option>
<option value="star" data-icon="fa-star" data-subtext="star"></option>
<option value="star-o" data-icon="fa-star-o" data-subtext="star-o"></option>
<option value="user" data-icon="fa-user" data-subtext="user"></option>
<option value="film" data-icon="fa-film" data-subtext="film"></option>
<option value="th-large" data-icon="fa-th-large" data-subtext="th-large"></option>
<option value="th" data-icon="fa-th" data-subtext="th"></option>
<option value="th-list" data-icon="fa-th-list" data-subtext="th-list"></option>
<option value="check" data-icon="fa-check" data-subtext="check"></option>
<option value="times" data-icon="fa-times" data-subtext="times"></option>
<option value="search-plus" data-icon="fa-search-plus" data-subtext="search-plus"></option>
<option value="search-minus" data-icon="fa-search-minus" data-subtext="search-minus"></option>
<option value="power-off" data-icon="fa-power-off" data-subtext="power-off"></option>
<option value="signal" data-icon="fa-signal" data-subtext="signal"></option>
<option value="cog" data-icon="fa-cog" data-subtext="cog"></option>
<option value="trash-o" data-icon="fa-trash-o" data-subtext="trash-o"></option>
<option value="home" data-icon="fa-home" data-subtext="home"></option>
<option value="file-o" data-icon="fa-file-o" data-subtext="file-o"></option>
<option value="clock-o" data-icon="fa-clock-o" data-subtext="clock-o"></option>
<option value="road" data-icon="fa-road" data-subtext="road"></option>
<option value="download" data-icon="fa-download" data-subtext="download"></option>
<option value="arrow-circle-o-down" data-icon="fa-arrow-circle-o-down" data-subtext="arrow-circle-o-down"></option>
<option value="arrow-circle-o-up" data-icon="fa-arrow-circle-o-up" data-subtext="arrow-circle-o-up"></option>
<option value="inbox" data-icon="fa-inbox" data-subtext="inbox"></option>
<option value="play-circle-o" data-icon="fa-play-circle-o" data-subtext="play-circle-o"></option>
<option value="repeat" data-icon="fa-repeat" data-subtext="repeat"></option>
<option value="refresh" data-icon="fa-refresh" data-subtext="refresh"></option>
<option value="list-alt" data-icon="fa-list-alt" data-subtext="list-alt"></option>
<option value="lock" data-icon="fa-lock" data-subtext="lock"></option>
<option value="flag" data-icon="fa-flag" data-subtext="flag"></option>
<option value="headphones" data-icon="fa-headphones" data-subtext="headphones"></option>
<option value="volume-off" data-icon="fa-volume-off" data-subtext="volume-off"></option>
<option value="volume-down" data-icon="fa-volume-down" data-subtext="volume-down"></option>
<option value="volume-up" data-icon="fa-volume-up" data-subtext="volume-up"></option>
<option value="qrcode" data-icon="fa-qrcode" data-subtext="qrcode"></option>
<option value="barcode" data-icon="fa-barcode" data-subtext="barcode"></option>
<option value="tag" data-icon="fa-tag" data-subtext="tag"></option>
<option value="tags" data-icon="fa-tags" data-subtext="tags"></option>
<option value="book" data-icon="fa-book" data-subtext="book"></option>
<option value="bookmark" data-icon="fa-bookmark" data-subtext="bookmark"></option>
<option value="print" data-icon="fa-print" data-subtext="print"></option>
<option value="camera" data-icon="fa-camera" data-subtext="camera"></option>
<option value="font" data-icon="fa-font" data-subtext="font"></option>
<option value="bold" data-icon="fa-bold" data-subtext="bold"></option>
<option value="italic" data-icon="fa-italic" data-subtext="italic"></option>
<option value="text-height" data-icon="fa-text-height" data-subtext="text-height"></option>
<option value="text-width" data-icon="fa-text-width" data-subtext="text-width"></option>
<option value="align-left" data-icon="fa-align-left" data-subtext="align-left"></option>
<option value="align-center" data-icon="fa-align-center" data-subtext="align-center"></option>
<option value="align-right" data-icon="fa-align-right" data-subtext="align-right"></option>
<option value="align-justify" data-icon="fa-align-justify" data-subtext="align-justify"></option>
<option value="list" data-icon="fa-list" data-subtext="list"></option>
<option value="outdent" data-icon="fa-outdent" data-subtext="outdent"></option>
<option value="indent" data-icon="fa-indent" data-subtext="indent"></option>
<option value="video-camera" data-icon="fa-video-camera" data-subtext="video-camera"></option>
<option value="picture-o" data-icon="fa-picture-o" data-subtext="picture-o"></option>
<option value="pencil" data-icon="fa-pencil" data-subtext="pencil"></option>
<option value="map-marker" data-icon="fa-map-marker" data-subtext="map-marker"></option>
<option value="adjust" data-icon="fa-adjust" data-subtext="adjust"></option>
<option value="tint" data-icon="fa-tint" data-subtext="tint"></option>
<option value="pencil-square-o" data-icon="fa-pencil-square-o" data-subtext="pencil-square-o"></option>
<option value="share-square-o" data-icon="fa-share-square-o" data-subtext="share-square-o"></option>
<option value="check-square-o" data-icon="fa-check-square-o" data-subtext="check-square-o"></option>
<option value="arrows" data-icon="fa-arrows" data-subtext="arrows"></option>
<option value="step-backward" data-icon="fa-step-backward" data-subtext="step-backward"></option>
<option value="fast-backward" data-icon="fa-fast-backward" data-subtext="fast-backward"></option>
<option value="backward" data-icon="fa-backward" data-subtext="backward"></option>
<option value="play" data-icon="fa-play" data-subtext="play"></option>
<option value="pause" data-icon="fa-pause" data-subtext="pause"></option>
<option value="stop" data-icon="fa-stop" data-subtext="stop"></option>
<option value="forward" data-icon="fa-forward" data-subtext="forward"></option>
<option value="fast-forward" data-icon="fa-fast-forward" data-subtext="fast-forward"></option>
<option value="step-forward" data-icon="fa-step-forward" data-subtext="step-forward"></option>
<option value="eject" data-icon="fa-eject" data-subtext="eject"></option>
<option value="chevron-left" data-icon="fa-chevron-left" data-subtext="chevron-left"></option>
<option value="chevron-right" data-icon="fa-chevron-right" data-subtext="chevron-right"></option>
<option value="plus-circle" data-icon="fa-plus-circle" data-subtext="plus-circle"></option>
<option value="minus-circle" data-icon="fa-minus-circle" data-subtext="minus-circle"></option>
<option value="times-circle" data-icon="fa-times-circle" data-subtext="times-circle"></option>
<option value="check-circle" data-icon="fa-check-circle" data-subtext="check-circle"></option>
<option value="question-circle" data-icon="fa-question-circle" data-subtext="question-circle"></option>
<option value="info-circle" data-icon="fa-info-circle" data-subtext="info-circle"></option>
<option value="crosshairs" data-icon="fa-crosshairs" data-subtext="crosshairs"></option>
<option value="times-circle-o" data-icon="fa-times-circle-o" data-subtext="times-circle-o"></option>
<option value="check-circle-o" data-icon="fa-check-circle-o" data-subtext="check-circle-o"></option>
<option value="ban" data-icon="fa-ban" data-subtext="ban"></option>
<option value="arrow-left" data-icon="fa-arrow-left" data-subtext="arrow-left"></option>
<option value="arrow-right" data-icon="fa-arrow-right" data-subtext="arrow-right"></option>
<option value="arrow-up" data-icon="fa-arrow-up" data-subtext="arrow-up"></option>
<option value="arrow-down" data-icon="fa-arrow-down" data-subtext="arrow-down"></option>
<option value="share" data-icon="fa-share" data-subtext="share"></option>
<option value="expand" data-icon="fa-expand" data-subtext="expand"></option>
<option value="compress" data-icon="fa-compress" data-subtext="compress"></option>
<option value="plus" data-icon="fa-plus" data-subtext="plus"></option>
<option value="minus" data-icon="fa-minus" data-subtext="minus"></option>
<option value="asterisk" data-icon="fa-asterisk" data-subtext="asterisk"></option>
<option value="exclamation-circle" data-icon="fa-exclamation-circle" data-subtext="exclamation-circle"></option>
<option value="gift" data-icon="fa-gift" data-subtext="gift"></option>
<option value="leaf" data-icon="fa-leaf" data-subtext="leaf"></option>
<option value="fire" data-icon="fa-fire" data-subtext="fire"></option>
<option value="eye" data-icon="fa-eye" data-subtext="eye"></option>
<option value="eye-slash" data-icon="fa-eye-slash" data-subtext="eye-slash"></option>
<option value="warning" data-icon="fa-warning" data-subtext="warning"></option>
<option value="plane" data-icon="fa-plane" data-subtext="plane"></option>
<option value="calendar" data-icon="fa-calendar" data-subtext="calendar"></option>
<option value="random" data-icon="fa-random" data-subtext="random"></option>
<option value="comment" data-icon="fa-comment" data-subtext="comment"></option>
<option value="magnet" data-icon="fa-magnet" data-subtext="magnet"></option>
<option value="chevron-up" data-icon="fa-chevron-up" data-subtext="chevron-up"></option>
<option value="chevron-down" data-icon="fa-chevron-down" data-subtext="chevron-down"></option>
<option value="retweet" data-icon="fa-retweet" data-subtext="retweet"></option>
<option value="shopping-cart" data-icon="fa-shopping-cart" data-subtext="shopping-cart"></option>
<option value="folder" data-icon="fa-folder" data-subtext="folder"></option>
<option value="folder-open" data-icon="fa-folder-open" data-subtext="folder-open"></option>
<option value="arrows-v" data-icon="fa-arrows-v" data-subtext="arrows-v"></option>
<option value="arrows-h" data-icon="fa-arrows-h" data-subtext="arrows-h"></option>
<option value="bar-chart" data-icon="fa-bar-chart" data-subtext="bar-chart"></option>
<option value="twitter-square" data-icon="fa-twitter-square" data-subtext="twitter-square"></option>
<option value="facebook-square" data-icon="fa-facebook-square" data-subtext="facebook-square"></option>
<option value="camera-retro" data-icon="fa-camera-retro" data-subtext="camera-retro"></option>
<option value="key" data-icon="fa-key" data-subtext="key"></option>
<option value="cogs" data-icon="fa-cogs" data-subtext="cogs"></option>
<option value="comments" data-icon="fa-comments" data-subtext="comments"></option>
<option value="thumbs-o-up" data-icon="fa-thumbs-o-up" data-subtext="thumbs-o-up"></option>
<option value="thumbs-o-down" data-icon="fa-thumbs-o-down" data-subtext="thumbs-o-down"></option>
<option value="star-half" data-icon="fa-star-half" data-subtext="star-half"></option>
<option value="heart-o" data-icon="fa-heart-o" data-subtext="heart-o"></option>
<option value="sign-out" data-icon="fa-sign-out" data-subtext="sign-out"></option>
<option value="linkedin-square" data-icon="fa-linkedin-square" data-subtext="linkedin-square"></option>
<option value="thumb-tack" data-icon="fa-thumb-tack" data-subtext="thumb-tack"></option>
<option value="external-link" data-icon="fa-external-link" data-subtext="external-link"></option>
<option value="sign-in" data-icon="fa-sign-in" data-subtext="sign-in"></option>
<option value="trophy" data-icon="fa-trophy" data-subtext="trophy"></option>
<option value="github-square" data-icon="fa-github-square" data-subtext="github-square"></option>
<option value="upload" data-icon="fa-upload" data-subtext="upload"></option>
<option value="lemon-o" data-icon="fa-lemon-o" data-subtext="lemon-o"></option>
<option value="phone" data-icon="fa-phone" data-subtext="phone"></option>
<option value="square-o" data-icon="fa-square-o" data-subtext="square-o"></option>
<option value="bookmark-o" data-icon="fa-bookmark-o" data-subtext="bookmark-o"></option>
<option value="phone-square" data-icon="fa-phone-square" data-subtext="phone-square"></option>
<option value="twitter" data-icon="fa-twitter" data-subtext="twitter"></option>
<option value="facebook" data-icon="fa-facebook" data-subtext="facebook"></option>
<option value="github" data-icon="fa-github" data-subtext="github"></option>
<option value="unlock" data-icon="fa-unlock" data-subtext="unlock"></option>
<option value="credit-card" data-icon="fa-credit-card" data-subtext="credit-card"></option>
<option value="rss" data-icon="fa-rss" data-subtext="rss"></option>
<option value="hdd-o" data-icon="fa-hdd-o" data-subtext="hdd-o"></option>
<option value="bullhorn" data-icon="fa-bullhorn" data-subtext="bullhorn"></option>
<option value="bell" data-icon="fa-bell" data-subtext="bell"></option>
<option value="certificate" data-icon="fa-certificate" data-subtext="certificate"></option>
<option value="hand-o-right" data-icon="fa-hand-o-right" data-subtext="hand-o-right"></option>
<option value="hand-o-left" data-icon="fa-hand-o-left" data-subtext="hand-o-left"></option>
<option value="hand-o-up" data-icon="fa-hand-o-up" data-subtext="hand-o-up"></option>
<option value="hand-o-down" data-icon="fa-hand-o-down" data-subtext="hand-o-down"></option>
<option value="arrow-circle-left" data-icon="fa-arrow-circle-left" data-subtext="arrow-circle-left"></option>
<option value="arrow-circle-right" data-icon="fa-arrow-circle-right" data-subtext="arrow-circle-right"></option>
<option value="arrow-circle-up" data-icon="fa-arrow-circle-up" data-subtext="arrow-circle-up"></option>
<option value="arrow-circle-down" data-icon="fa-arrow-circle-down" data-subtext="arrow-circle-down"></option>
<option value="globe" data-icon="fa-globe" data-subtext="globe"></option>
<option value="wrench" data-icon="fa-wrench" data-subtext="wrench"></option>
<option value="tasks" data-icon="fa-tasks" data-subtext="tasks"></option>
<option value="filter" data-icon="fa-filter" data-subtext="filter"></option>
<option value="briefcase" data-icon="fa-briefcase" data-subtext="briefcase"></option>
<option value="arrows-alt" data-icon="fa-arrows-alt" data-subtext="arrows-alt"></option>
<option value="users" data-icon="fa-users" data-subtext="users"></option>
<option value="link" data-icon="fa-link" data-subtext="link"></option>
<option value="cloud" data-icon="fa-cloud" data-subtext="cloud"></option>
<option value="flask" data-icon="fa-flask" data-subtext="flask"></option>
<option value="cut" data-icon="fa-cut" data-subtext="cut"></option>
<option value="files-o" data-icon="fa-files-o" data-subtext="files-o"></option>
<option value="paperclip" data-icon="fa-paperclip" data-subtext="paperclip"></option>
<option value="save" data-icon="fa-save" data-subtext="save"></option>
<option value="square" data-icon="fa-square" data-subtext="square"></option>
<option value="bars" data-icon="fa-bars" data-subtext="bars"></option>
<option value="list-ul" data-icon="fa-list-ul" data-subtext="list-ul"></option>
<option value="list-ol" data-icon="fa-list-ol" data-subtext="list-ol"></option>
<option value="strikethrough" data-icon="fa-strikethrough" data-subtext="strikethrough"></option>
<option value="underline" data-icon="fa-underline" data-subtext="underline"></option>
<option value="table" data-icon="fa-table" data-subtext="table"></option>
<option value="magic" data-icon="fa-magic" data-subtext="magic"></option>
<option value="truck" data-icon="fa-truck" data-subtext="truck"></option>
<option value="pinterest" data-icon="fa-pinterest" data-subtext="pinterest"></option>
<option value="pinterest-square" data-icon="fa-pinterest-square" data-subtext="pinterest-square"></option>
<option value="google-plus-square" data-icon="fa-google-plus-square" data-subtext="google-plus-square"></option>
<option value="google-plus" data-icon="fa-google-plus" data-subtext="google-plus"></option>
<option value="money" data-icon="fa-money" data-subtext="money"></option>
<option value="caret-down" data-icon="fa-caret-down" data-subtext="caret-down"></option>
<option value="caret-up" data-icon="fa-caret-up" data-subtext="caret-up"></option>
<option value="caret-left" data-icon="fa-caret-left" data-subtext="caret-left"></option>
<option value="caret-right" data-icon="fa-caret-right" data-subtext="caret-right"></option>
<option value="columns" data-icon="fa-columns" data-subtext="columns"></option>
<option value="sort" data-icon="fa-sort" data-subtext="sort"></option>
<option value="sort-desc" data-icon="fa-sort-desc" data-subtext="sort-desc"></option>
<option value="sort-asc" data-icon="fa-sort-asc" data-subtext="sort-asc"></option>
<option value="envelope" data-icon="fa-envelope" data-subtext="envelope"></option>
<option value="linkedin" data-icon="fa-linkedin" data-subtext="linkedin"></option>
<option value="undo" data-icon="fa-undo" data-subtext="undo"></option>
<option value="gavel" data-icon="fa-gavel" data-subtext="gavel"></option>
<option value="tachometer" data-icon="fa-tachometer" data-subtext="tachometer"></option>
<option value="comment-o" data-icon="fa-comment-o" data-subtext="comment-o"></option>
<option value="comments-o" data-icon="fa-comments-o" data-subtext="comments-o"></option>
<option value="bolt" data-icon="fa-bolt" data-subtext="bolt"></option>
<option value="sitemap" data-icon="fa-sitemap" data-subtext="sitemap"></option>
<option value="umbrella" data-icon="fa-umbrella" data-subtext="umbrella"></option>
<option value="paste" data-icon="fa-paste" data-subtext="paste"></option>
<option value="lightbulb-o" data-icon="fa-lightbulb-o" data-subtext="lightbulb-o"></option>
<option value="exchange" data-icon="fa-exchange" data-subtext="exchange"></option>
<option value="cloud-download" data-icon="fa-cloud-download" data-subtext="cloud-download"></option>
<option value="cloud-upload" data-icon="fa-cloud-upload" data-subtext="cloud-upload"></option>
<option value="user-md" data-icon="fa-user-md" data-subtext="user-md"></option>
<option value="stethoscope" data-icon="fa-stethoscope" data-subtext="stethoscope"></option>
<option value="suitcase" data-icon="fa-suitcase" data-subtext="suitcase"></option>
<option value="bell-o" data-icon="fa-bell-o" data-subtext="bell-o"></option>
<option value="coffee" data-icon="fa-coffee" data-subtext="coffee"></option>
<option value="cutlery" data-icon="fa-cutlery" data-subtext="cutlery"></option>
<option value="file-text-o" data-icon="fa-file-text-o" data-subtext="file-text-o"></option>
<option value="building-o" data-icon="fa-building-o" data-subtext="building-o"></option>
<option value="hospital-o" data-icon="fa-hospital-o" data-subtext="hospital-o"></option>
<option value="ambulance" data-icon="fa-ambulance" data-subtext="ambulance"></option>
<option value="medkit" data-icon="fa-medkit" data-subtext="medkit"></option>
<option value="fighter-jet" data-icon="fa-fighter-jet" data-subtext="fighter-jet"></option>
<option value="beer" data-icon="fa-beer" data-subtext="beer"></option>
<option value="h-square" data-icon="fa-h-square" data-subtext="h-square"></option>
<option value="plus-square" data-icon="fa-plus-square" data-subtext="plus-square"></option>
<option value="angle-double-left" data-icon="fa-angle-double-left" data-subtext="angle-double-left"></option>
<option value="angle-double-right" data-icon="fa-angle-double-right" data-subtext="angle-double-right"></option>
<option value="angle-double-up" data-icon="fa-angle-double-up" data-subtext="angle-double-up"></option>
<option value="angle-double-down" data-icon="fa-angle-double-down" data-subtext="angle-double-down"></option>
<option value="angle-left" data-icon="fa-angle-left" data-subtext="angle-left"></option>
<option value="angle-right" data-icon="fa-angle-right" data-subtext="angle-right"></option>
<option value="angle-up" data-icon="fa-angle-up" data-subtext="angle-up"></option>
<option value="angle-down" data-icon="fa-angle-down" data-subtext="angle-down"></option>
<option value="desktop" data-icon="fa-desktop" data-subtext="desktop"></option>
<option value="laptop" data-icon="fa-laptop" data-subtext="laptop"></option>
<option value="tablet" data-icon="fa-tablet" data-subtext="tablet"></option>
<option value="mobile" data-icon="fa-mobile" data-subtext="mobile"></option>
<option value="circle-o" data-icon="fa-circle-o" data-subtext="circle-o"></option>
<option value="quote-left" data-icon="fa-quote-left" data-subtext="quote-left"></option>
<option value="quote-right" data-icon="fa-quote-right" data-subtext="quote-right"></option>
<option value="spinner" data-icon="fa-spinner" data-subtext="spinner"></option>
<option value="circle" data-icon="fa-circle" data-subtext="circle"></option>
<option value="reply" data-icon="fa-reply" data-subtext="reply"></option>
<option value="github-alt" data-icon="fa-github-alt" data-subtext="github-alt"></option>
<option value="folder-o" data-icon="fa-folder-o" data-subtext="folder-o"></option>
<option value="folder-open-o" data-icon="fa-folder-open-o" data-subtext="folder-open-o"></option>
<option value="smile-o" data-icon="fa-smile-o" data-subtext="smile-o"></option>
<option value="frown-o" data-icon="fa-frown-o" data-subtext="frown-o"></option>
<option value="meh-o" data-icon="fa-meh-o" data-subtext="meh-o"></option>
<option value="gamepad" data-icon="fa-gamepad" data-subtext="gamepad"></option>
<option value="keyboard-o" data-icon="fa-keyboard-o" data-subtext="keyboard-o"></option>
<option value="flag-o" data-icon="fa-flag-o" data-subtext="flag-o"></option>
<option value="flag-checkered" data-icon="fa-flag-checkered" data-subtext="flag-checkered"></option>
<option value="terminal" data-icon="fa-terminal" data-subtext="terminal"></option>
<option value="code" data-icon="fa-code" data-subtext="code"></option>
<option value="mail-reply-all" data-icon="fa-mail-reply-all" data-subtext="mail-reply-all"></option>
<option value="reply-all" data-icon="fa-reply-all" data-subtext="reply-all"></option>
<option value="star-half-o" data-icon="fa-star-half-o" data-subtext="star-half-o"></option>
<option value="location-arrow" data-icon="fa-location-arrow" data-subtext="location-arrow"></option>
<option value="crop" data-icon="fa-crop" data-subtext="crop"></option>
<option value="code-fork" data-icon="fa-code-fork" data-subtext="code-fork"></option>
<option value="chain-broken" data-icon="fa-chain-broken" data-subtext="chain-broken"></option>
<option value="question" data-icon="fa-question" data-subtext="question"></option>
<option value="info" data-icon="fa-info" data-subtext="info"></option>
<option value="exclamation" data-icon="fa-exclamation" data-subtext="exclamation"></option>
<option value="superscript" data-icon="fa-superscript" data-subtext="superscript"></option>
<option value="subscript" data-icon="fa-subscript" data-subtext="subscript"></option>
<option value="eraser" data-icon="fa-eraser" data-subtext="eraser"></option>
<option value="puzzle-piece" data-icon="fa-puzzle-piece" data-subtext="puzzle-piece"></option>
<option value="microphone" data-icon="fa-microphone" data-subtext="microphone"></option>
<option value="microphone-slash" data-icon="fa-microphone-slash" data-subtext="microphone-slash"></option>
<option value="shield" data-icon="fa-shield" data-subtext="shield"></option>
<option value="calendar-o" data-icon="fa-calendar-o" data-subtext="calendar-o"></option>
<option value="fire-extinguisher" data-icon="fa-fire-extinguisher" data-subtext="fire-extinguisher"></option>
<option value="rocket" data-icon="fa-rocket" data-subtext="rocket"></option>
<option value="maxcdn" data-icon="fa-maxcdn" data-subtext="maxcdn"></option>
<option value="chevron-circle-left" data-icon="fa-chevron-circle-left" data-subtext="chevron-circle-left"></option>
<option value="chevron-circle-right" data-icon="fa-chevron-circle-right" data-subtext="chevron-circle-right"></option>
<option value="chevron-circle-up" data-icon="fa-chevron-circle-up" data-subtext="chevron-circle-up"></option>
<option value="chevron-circle-down" data-icon="fa-chevron-circle-down" data-subtext="chevron-circle-down"></option>
<option value="html5" data-icon="fa-html5" data-subtext="html5"></option>
<option value="css3" data-icon="fa-css3" data-subtext="css3"></option>
<option value="anchor" data-icon="fa-anchor" data-subtext="anchor"></option>
<option value="unlock-alt" data-icon="fa-unlock-alt" data-subtext="unlock-alt"></option>
<option value="bullseye" data-icon="fa-bullseye" data-subtext="bullseye"></option>
<option value="ellipsis-h" data-icon="fa-ellipsis-h" data-subtext="ellipsis-h"></option>
<option value="ellipsis-v" data-icon="fa-ellipsis-v" data-subtext="ellipsis-v"></option>
<option value="rss-square" data-icon="fa-rss-square" data-subtext="rss-square"></option>
<option value="play-circle" data-icon="fa-play-circle" data-subtext="play-circle"></option>
<option value="ticket" data-icon="fa-ticket" data-subtext="ticket"></option>
<option value="minus-square" data-icon="fa-minus-square" data-subtext="minus-square"></option>
<option value="minus-square-o" data-icon="fa-minus-square-o" data-subtext="minus-square-o"></option>
<option value="level-up" data-icon="fa-level-up" data-subtext="level-up"></option>
<option value="level-down" data-icon="fa-level-down" data-subtext="level-down"></option>
<option value="check-square" data-icon="fa-check-square" data-subtext="check-square"></option>
<option value="pencil-square" data-icon="fa-pencil-square" data-subtext="pencil-square"></option>
<option value="external-link-square" data-icon="fa-external-link-square" data-subtext="external-link-square"></option>
<option value="share-square" data-icon="fa-share-square" data-subtext="share-square"></option>
<option value="compass" data-icon="fa-compass" data-subtext="compass"></option>
<option value="toggle-down" data-icon="fa-toggle-down" data-subtext="toggle-down"></option>
<option value="toggle-up" data-icon="fa-toggle-up" data-subtext="toggle-up"></option>
<option value="toggle-right" data-icon="fa-toggle-right" data-subtext="toggle-right"></option>
<option value="euro" data-icon="fa-euro" data-subtext="euro"></option>
<option value="gbp" data-icon="fa-gbp" data-subtext="gbp"></option>
<option value="usd" data-icon="fa-usd" data-subtext="usd"></option>
<option value="inr" data-icon="fa-inr" data-subtext="inr"></option>
<option value="jpy" data-icon="fa-jpy" data-subtext="jpy"></option>
<option value="rub" data-icon="fa-rub" data-subtext="rub"></option>
<option value="krw" data-icon="fa-krw" data-subtext="krw"></option>
<option value="btc" data-icon="fa-btc" data-subtext="btc"></option>
<option value="file" data-icon="fa-file" data-subtext="file"></option>
<option value="file-text" data-icon="fa-file-text" data-subtext="file-text"></option>
<option value="sort-alpha-asc" data-icon="fa-sort-alpha-asc" data-subtext="sort-alpha-asc"></option>
<option value="sort-alpha-desc" data-icon="fa-sort-alpha-desc" data-subtext="sort-alpha-desc"></option>
<option value="sort-amount-asc" data-icon="fa-sort-amount-asc" data-subtext="sort-amount-asc"></option>
<option value="sort-amount-desc" data-icon="fa-sort-amount-desc" data-subtext="sort-amount-desc"></option>
<option value="sort-numeric-asc" data-icon="fa-sort-numeric-asc" data-subtext="sort-numeric-asc"></option>
<option value="sort-numeric-desc" data-icon="fa-sort-numeric-desc" data-subtext="sort-numeric-desc"></option>
<option value="thumbs-up" data-icon="fa-thumbs-up" data-subtext="thumbs-up"></option>
<option value="thumbs-down" data-icon="fa-thumbs-down" data-subtext="thumbs-down"></option>
<option value="youtube-square" data-icon="fa-youtube-square" data-subtext="youtube-square"></option>
<option value="youtube" data-icon="fa-youtube" data-subtext="youtube"></option>
<option value="xing" data-icon="fa-xing" data-subtext="xing"></option>
<option value="xing-square" data-icon="fa-xing-square" data-subtext="xing-square"></option>
<option value="youtube-play" data-icon="fa-youtube-play" data-subtext="youtube-play"></option>
<option value="dropbox" data-icon="fa-dropbox" data-subtext="dropbox"></option>
<option value="stack-overflow" data-icon="fa-stack-overflow" data-subtext="stack-overflow"></option>
<option value="instagram" data-icon="fa-instagram" data-subtext="instagram"></option>
<option value="flickr" data-icon="fa-flickr" data-subtext="flickr"></option>
<option value="adn" data-icon="fa-adn" data-subtext="adn"></option>
<option value="bitbucket" data-icon="fa-bitbucket" data-subtext="bitbucket"></option>
<option value="bitbucket-square" data-icon="fa-bitbucket-square" data-subtext="bitbucket-square"></option>
<option value="tumblr" data-icon="fa-tumblr" data-subtext="tumblr"></option>
<option value="tumblr-square" data-icon="fa-tumblr-square" data-subtext="tumblr-square"></option>
<option value="long-arrow-down" data-icon="fa-long-arrow-down" data-subtext="long-arrow-down"></option>
<option value="long-arrow-up" data-icon="fa-long-arrow-up" data-subtext="long-arrow-up"></option>
<option value="long-arrow-left" data-icon="fa-long-arrow-left" data-subtext="long-arrow-left"></option>
<option value="long-arrow-right" data-icon="fa-long-arrow-right" data-subtext="long-arrow-right"></option>
<option value="apple" data-icon="fa-apple" data-subtext="apple"></option>
<option value="windows" data-icon="fa-windows" data-subtext="windows"></option>
<option value="android" data-icon="fa-android" data-subtext="android"></option>
<option value="linux" data-icon="fa-linux" data-subtext="linux"></option>
<option value="dribbble" data-icon="fa-dribbble" data-subtext="dribbble"></option>
<option value="skype" data-icon="fa-skype" data-subtext="skype"></option>
<option value="foursquare" data-icon="fa-foursquare" data-subtext="foursquare"></option>
<option value="trello" data-icon="fa-trello" data-subtext="trello"></option>
<option value="female" data-icon="fa-female" data-subtext="female"></option>
<option value="male" data-icon="fa-male" data-subtext="male"></option>
<option value="gittip" data-icon="fa-gittip" data-subtext="gittip"></option>
<option value="sun-o" data-icon="fa-sun-o" data-subtext="sun-o"></option>
<option value="moon-o" data-icon="fa-moon-o" data-subtext="moon-o"></option>
<option value="archive" data-icon="fa-archive" data-subtext="archive"></option>
<option value="bug" data-icon="fa-bug" data-subtext="bug"></option>
<option value="vk" data-icon="fa-vk" data-subtext="vk"></option>
<option value="weibo" data-icon="fa-weibo" data-subtext="weibo"></option>
<option value="renren" data-icon="fa-renren" data-subtext="renren"></option>
<option value="pagelines" data-icon="fa-pagelines" data-subtext="pagelines"></option>
<option value="stack-exchange" data-icon="fa-stack-exchange" data-subtext="stack-exchange"></option>
<option value="arrow-circle-o-right" data-icon="fa-arrow-circle-o-right" data-subtext="arrow-circle-o-right"></option>
<option value="arrow-circle-o-left" data-icon="fa-arrow-circle-o-left" data-subtext="arrow-circle-o-left"></option>
<option value="toggle-left" data-icon="fa-toggle-left" data-subtext="toggle-left"></option>
<option value="dot-circle-o" data-icon="fa-dot-circle-o" data-subtext="dot-circle-o"></option>
<option value="wheelchair" data-icon="fa-wheelchair" data-subtext="wheelchair"></option>
<option value="vimeo-square" data-icon="fa-vimeo-square" data-subtext="vimeo-square"></option>
<option value="try" data-icon="fa-try" data-subtext="try"></option>
<option value="plus-square-o" data-icon="fa-plus-square-o" data-subtext="plus-square-o"></option>
<option value="space-shuttle" data-icon="fa-space-shuttle" data-subtext="space-shuttle"></option>
<option value="slack" data-icon="fa-slack" data-subtext="slack"></option>
<option value="envelope-square" data-icon="fa-envelope-square" data-subtext="envelope-square"></option>
<option value="wordpress" data-icon="fa-wordpress" data-subtext="wordpress"></option>
<option value="openid" data-icon="fa-openid" data-subtext="openid"></option>
<option value="institution" data-icon="fa-institution" data-subtext="institution"></option>
<option value="graduation-cap" data-icon="fa-graduation-cap" data-subtext="graduation-cap"></option>
<option value="yahoo" data-icon="fa-yahoo" data-subtext="yahoo"></option>
<option value="google" data-icon="fa-google" data-subtext="google"></option>
<option value="reddit" data-icon="fa-reddit" data-subtext="reddit"></option>
<option value="reddit-square" data-icon="fa-reddit-square" data-subtext="reddit-square"></option>
<option value="stumbleupon-circle" data-icon="fa-stumbleupon-circle" data-subtext="stumbleupon-circle"></option>
<option value="stumbleupon" data-icon="fa-stumbleupon" data-subtext="stumbleupon"></option>
<option value="delicious" data-icon="fa-delicious" data-subtext="delicious"></option>
<option value="digg" data-icon="fa-digg" data-subtext="digg"></option>
<option value="pied-piper" data-icon="fa-pied-piper" data-subtext="pied-piper"></option>
<option value="pied-piper-alt" data-icon="fa-pied-piper-alt" data-subtext="pied-piper-alt"></option>
<option value="drupal" data-icon="fa-drupal" data-subtext="drupal"></option>
<option value="joomla" data-icon="fa-joomla" data-subtext="joomla"></option>
<option value="language" data-icon="fa-language" data-subtext="language"></option>
<option value="fax" data-icon="fa-fax" data-subtext="fax"></option>
<option value="building" data-icon="fa-building" data-subtext="building"></option>
<option value="child" data-icon="fa-child" data-subtext="child"></option>
<option value="paw" data-icon="fa-paw" data-subtext="paw"></option>
<option value="spoon" data-icon="fa-spoon" data-subtext="spoon"></option>
<option value="cube" data-icon="fa-cube" data-subtext="cube"></option>
<option value="cubes" data-icon="fa-cubes" data-subtext="cubes"></option>
<option value="behance" data-icon="fa-behance" data-subtext="behance"></option>
<option value="behance-square" data-icon="fa-behance-square" data-subtext="behance-square"></option>
<option value="steam" data-icon="fa-steam" data-subtext="steam"></option>
<option value="steam-square" data-icon="fa-steam-square" data-subtext="steam-square"></option>
<option value="recycle" data-icon="fa-recycle" data-subtext="recycle"></option>
<option value="car" data-icon="fa-car" data-subtext="car"></option>
<option value="taxi" data-icon="fa-taxi" data-subtext="taxi"></option>
<option value="tree" data-icon="fa-tree" data-subtext="tree"></option>
<option value="spotify" data-icon="fa-spotify" data-subtext="spotify"></option>
<option value="deviantart" data-icon="fa-deviantart" data-subtext="deviantart"></option>
<option value="soundcloud" data-icon="fa-soundcloud" data-subtext="soundcloud"></option>
<option value="database" data-icon="fa-database" data-subtext="database"></option>
<option value="file-pdf-o" data-icon="fa-file-pdf-o" data-subtext="file-pdf-o"></option>
<option value="file-word-o" data-icon="fa-file-word-o" data-subtext="file-word-o"></option>
<option value="file-excel-o" data-icon="fa-file-excel-o" data-subtext="file-excel-o"></option>
<option value="file-powerpoint-o" data-icon="fa-file-powerpoint-o" data-subtext="file-powerpoint-o"></option>
<option value="file-image-o" data-icon="fa-file-image-o" data-subtext="file-image-o"></option>
<option value="file-zip-o" data-icon="fa-file-zip-o" data-subtext="file-zip-o"></option>
<option value="file-audio-o" data-icon="fa-file-audio-o" data-subtext="file-audio-o"></option>
<option value="file-video-o" data-icon="fa-file-video-o" data-subtext="file-video-o"></option>
<option value="file-code-o" data-icon="fa-file-code-o" data-subtext="file-code-o"></option>
<option value="vine" data-icon="fa-vine" data-subtext="vine"></option>
<option value="codepen" data-icon="fa-codepen" data-subtext="codepen"></option>
<option value="jsfiddle" data-icon="fa-jsfiddle" data-subtext="jsfiddle"></option>
<option value="life-ring" data-icon="fa-life-ring" data-subtext="life-ring"></option>
<option value="circle-o-notch" data-icon="fa-circle-o-notch" data-subtext="circle-o-notch"></option>
<option value="ra" data-icon="fa-ra" data-subtext="ra"></option>
<option value="ge" data-icon="fa-ge" data-subtext="ge"></option>
<option value="git-square" data-icon="fa-git-square" data-subtext="git-square"></option>
<option value="git" data-icon="fa-git" data-subtext="git"></option>
<option value="hacker-news" data-icon="fa-hacker-news" data-subtext="hacker-news"></option>
<option value="tencent-weibo" data-icon="fa-tencent-weibo" data-subtext="tencent-weibo"></option>
<option value="qq" data-icon="fa-qq" data-subtext="qq"></option>
<option value="weixin" data-icon="fa-weixin" data-subtext="weixin"></option>
<option value="paper-plane" data-icon="fa-paper-plane" data-subtext="paper-plane"></option>
<option value="send-o" data-icon="fa-send-o" data-subtext="send-o"></option>
<option value="history" data-icon="fa-history" data-subtext="history"></option>
<option value="circle-thin" data-icon="fa-circle-thin" data-subtext="circle-thin"></option>
<option value="header" data-icon="fa-header" data-subtext="header"></option>
<option value="paragraph" data-icon="fa-paragraph" data-subtext="paragraph"></option>
<option value="sliders" data-icon="fa-sliders" data-subtext="sliders"></option>
<option value="share-alt" data-icon="fa-share-alt" data-subtext="share-alt"></option>
<option value="share-alt-square" data-icon="fa-share-alt-square" data-subtext="share-alt-square"></option>
<option value="bomb" data-icon="fa-bomb" data-subtext="bomb"></option>
<option value="futbol-o" data-icon="fa-futbol-o" data-subtext="futbol-o"></option>
<option value="tty" data-icon="fa-tty" data-subtext="tty"></option>
<option value="binoculars" data-icon="fa-binoculars" data-subtext="binoculars"></option>
<option value="plug" data-icon="fa-plug" data-subtext="plug"></option>
<option value="slideshare" data-icon="fa-slideshare" data-subtext="slideshare"></option>
<option value="twitch" data-icon="fa-twitch" data-subtext="twitch"></option>
<option value="yelp" data-icon="fa-yelp" data-subtext="yelp"></option>
<option value="newspaper-o" data-icon="fa-newspaper-o" data-subtext="newspaper-o"></option>
<option value="wifi" data-icon="fa-wifi" data-subtext="wifi"></option>
<option value="calculator" data-icon="fa-calculator" data-subtext="calculator"></option>
<option value="paypal" data-icon="fa-paypal" data-subtext="paypal"></option>
<option value="google-wallet" data-icon="fa-google-wallet" data-subtext="google-wallet"></option>
<option value="cc-visa" data-icon="fa-cc-visa" data-subtext="cc-visa"></option>
<option value="cc-mastercard" data-icon="fa-cc-mastercard" data-subtext="cc-mastercard"></option>
<option value="cc-discover" data-icon="fa-cc-discover" data-subtext="cc-discover"></option>
<option value="cc-amex" data-icon="fa-cc-amex" data-subtext="cc-amex"></option>
<option value="cc-paypal" data-icon="fa-cc-paypal" data-subtext="cc-paypal"></option>
<option value="cc-stripe" data-icon="fa-cc-stripe" data-subtext="cc-stripe"></option>
<option value="bell-slash" data-icon="fa-bell-slash" data-subtext="bell-slash"></option>
<option value="bell-slash-o" data-icon="fa-bell-slash-o" data-subtext="bell-slash-o"></option>
<option value="trash" data-icon="fa-trash" data-subtext="trash"></option>
<option value="copyright" data-icon="fa-copyright" data-subtext="copyright"></option>
<option value="at" data-icon="fa-at" data-subtext="at"></option>
<option value="eyedropper" data-icon="fa-eyedropper" data-subtext="eyedropper"></option>
<option value="paint-brush" data-icon="fa-paint-brush" data-subtext="paint-brush"></option>
<option value="birthday-cake" data-icon="fa-birthday-cake" data-subtext="birthday-cake"></option>
<option value="area-chart" data-icon="fa-area-chart" data-subtext="area-chart"></option>
<option value="pie-chart" data-icon="fa-pie-chart" data-subtext="pie-chart"></option>
<option value="line-chart" data-icon="fa-line-chart" data-subtext="line-chart"></option>
<option value="lastfm" data-icon="fa-lastfm" data-subtext="lastfm"></option>
<option value="lastfm-square" data-icon="fa-lastfm-square" data-subtext="lastfm-square"></option>
<option value="toggle-off" data-icon="fa-toggle-off" data-subtext="toggle-off"></option>
<option value="toggle-on" data-icon="fa-toggle-on" data-subtext="toggle-on"></option>
<option value="bicycle" data-icon="fa-bicycle" data-subtext="bicycle"></option>
<option value="bus" data-icon="fa-bus" data-subtext="bus"></option>
<option value="ioxhost" data-icon="fa-ioxhost" data-subtext="ioxhost"></option>
<option value="angellist" data-icon="fa-angellist" data-subtext="angellist"></option>
<option value="cc" data-icon="fa-cc" data-subtext="cc"></option>
<option value="ils" data-icon="fa-ils" data-subtext="ils"></option>
<option value="meanpath" data-icon="fa-meanpath" data-subtext="meanpath"></option>
<option value="buysellads" data-icon="fa-buysellads" data-subtext="buysellads"></option>
<option value="connectdevelop" data-icon="fa-connectdevelop" data-subtext="connectdevelop"></option>
<option value="dashcube" data-icon="fa-dashcube" data-subtext="dashcube"></option>
<option value="forumbee" data-icon="fa-forumbee" data-subtext="forumbee"></option>
<option value="leanpub" data-icon="fa-leanpub" data-subtext="leanpub"></option>
<option value="sellsy" data-icon="fa-sellsy" data-subtext="sellsy"></option>
<option value="shirtsinbulk" data-icon="fa-shirtsinbulk" data-subtext="shirtsinbulk"></option>
<option value="simplybuilt" data-icon="fa-simplybuilt" data-subtext="simplybuilt"></option>
<option value="skyatlas" data-icon="fa-skyatlas" data-subtext="skyatlas"></option>
<option value="cart-plus" data-icon="fa-cart-plus" data-subtext="cart-plus"></option>
<option value="cart-arrow-down" data-icon="fa-cart-arrow-down" data-subtext="cart-arrow-down"></option>
<option value="diamond" data-icon="fa-diamond" data-subtext="diamond"></option>
<option value="ship" data-icon="fa-ship" data-subtext="ship"></option>
<option value="user-secret" data-icon="fa-user-secret" data-subtext="user-secret"></option>
<option value="motorcycle" data-icon="fa-motorcycle" data-subtext="motorcycle"></option>
<option value="street-view" data-icon="fa-street-view" data-subtext="street-view"></option>
<option value="heartbeat" data-icon="fa-heartbeat" data-subtext="heartbeat"></option>
<option value="venus" data-icon="fa-venus" data-subtext="venus"></option>
<option value="mars" data-icon="fa-mars" data-subtext="mars"></option>
<option value="mercury" data-icon="fa-mercury" data-subtext="mercury"></option>
<option value="transgender" data-icon="fa-transgender" data-subtext="transgender"></option>
<option value="transgender-alt" data-icon="fa-transgender-alt" data-subtext="transgender-alt"></option>
<option value="venus-double" data-icon="fa-venus-double" data-subtext="venus-double"></option>
<option value="mars-double" data-icon="fa-mars-double" data-subtext="mars-double"></option>
<option value="venus-mars" data-icon="fa-venus-mars" data-subtext="venus-mars"></option>
<option value="mars-stroke" data-icon="fa-mars-stroke" data-subtext="mars-stroke"></option>
<option value="mars-stroke-v" data-icon="fa-mars-stroke-v" data-subtext="mars-stroke-v"></option>
<option value="mars-stroke-h" data-icon="fa-mars-stroke-h" data-subtext="mars-stroke-h"></option>
<option value="neuter" data-icon="fa-neuter" data-subtext="neuter"></option>
<option value="genderless" data-icon="fa-genderless" data-subtext="genderless"></option>
<option value="facebook-official" data-icon="fa-facebook-official" data-subtext="facebook-official"></option>
<option value="pinterest-p" data-icon="fa-pinterest-p" data-subtext="pinterest-p"></option>
<option value="whatsapp" data-icon="fa-whatsapp" data-subtext="whatsapp"></option>
<option value="server" data-icon="fa-server" data-subtext="server"></option>
<option value="user-plus" data-icon="fa-user-plus" data-subtext="user-plus"></option>
<option value="user-times" data-icon="fa-user-times" data-subtext="user-times"></option>
<option value="bed" data-icon="fa-bed" data-subtext="bed"></option>
<option value="viacoin" data-icon="fa-viacoin" data-subtext="viacoin"></option>
<option value="train" data-icon="fa-train" data-subtext="train"></option>
<option value="subway" data-icon="fa-subway" data-subtext="subway"></option>
<option value="medium" data-icon="fa-medium" data-subtext="medium"></option>
<option value="yc" data-icon="fa-yc" data-subtext="yc"></option>
<option value="optin-monster" data-icon="fa-optin-monster" data-subtext="optin-monster"></option>
<option value="opencart" data-icon="fa-opencart" data-subtext="opencart"></option>
<option value="expeditedssl" data-icon="fa-expeditedssl" data-subtext="expeditedssl"></option>
<option value="battery-4" data-icon="fa-battery-4" data-subtext="battery-4"></option>
<option value="battery-3" data-icon="fa-battery-3" data-subtext="battery-3"></option>
<option value="battery-2" data-icon="fa-battery-2" data-subtext="battery-2"></option>
<option value="battery-1" data-icon="fa-battery-1" data-subtext="battery-1"></option>
<option value="battery-0" data-icon="fa-battery-0" data-subtext="battery-0"></option>
<option value="mouse-pointer" data-icon="fa-mouse-pointer" data-subtext="mouse-pointer"></option>
<option value="i-cursor" data-icon="fa-i-cursor" data-subtext="i-cursor"></option>
<option value="object-group" data-icon="fa-object-group" data-subtext="object-group"></option>
<option value="object-ungroup" data-icon="fa-object-ungroup" data-subtext="object-ungroup"></option>
<option value="sticky-note" data-icon="fa-sticky-note" data-subtext="sticky-note"></option>
<option value="sticky-note-o" data-icon="fa-sticky-note-o" data-subtext="sticky-note-o"></option>
<option value="cc-jcb" data-icon="fa-cc-jcb" data-subtext="cc-jcb"></option>
<option value="cc-diners-club" data-icon="fa-cc-diners-club" data-subtext="cc-diners-club"></option>
<option value="clone" data-icon="fa-clone" data-subtext="clone"></option>
<option value="balance-scale" data-icon="fa-balance-scale" data-subtext="balance-scale"></option>
<option value="hourglass-o" data-icon="fa-hourglass-o" data-subtext="hourglass-o"></option>
<option value="hourglass-1" data-icon="fa-hourglass-1" data-subtext="hourglass-1"></option>
<option value="hourglass-2" data-icon="fa-hourglass-2" data-subtext="hourglass-2"></option>
<option value="hourglass-3" data-icon="fa-hourglass-3" data-subtext="hourglass-3"></option>
<option value="hourglass" data-icon="fa-hourglass" data-subtext="hourglass"></option>
<option value="hand-rock-o" data-icon="fa-hand-rock-o" data-subtext="hand-rock-o"></option>
<option value="hand-paper-o" data-icon="fa-hand-paper-o" data-subtext="hand-paper-o"></option>
<option value="hand-scissors-o" data-icon="fa-hand-scissors-o" data-subtext="hand-scissors-o"></option>
<option value="hand-lizard-o" data-icon="fa-hand-lizard-o" data-subtext="hand-lizard-o"></option>
<option value="hand-spock-o" data-icon="fa-hand-spock-o" data-subtext="hand-spock-o"></option>
<option value="hand-pointer-o" data-icon="fa-hand-pointer-o" data-subtext="hand-pointer-o"></option>
<option value="hand-peace-o" data-icon="fa-hand-peace-o" data-subtext="hand-peace-o"></option>
<option value="trademark" data-icon="fa-trademark" data-subtext="trademark"></option>
<option value="registered" data-icon="fa-registered" data-subtext="registered"></option>
<option value="creative-commons" data-icon="fa-creative-commons" data-subtext="creative-commons"></option>
<option value="gg" data-icon="fa-gg" data-subtext="gg"></option>
<option value="gg-circle" data-icon="fa-gg-circle" data-subtext="gg-circle"></option>
<option value="tripadvisor" data-icon="fa-tripadvisor" data-subtext="tripadvisor"></option>
<option value="odnoklassniki" data-icon="fa-odnoklassniki" data-subtext="odnoklassniki"></option>
<option value="odnoklassniki-square" data-icon="fa-odnoklassniki-square" data-subtext="odnoklassniki-square"></option>
<option value="get-pocket" data-icon="fa-get-pocket" data-subtext="get-pocket"></option>
<option value="wikipedia-w" data-icon="fa-wikipedia-w" data-subtext="wikipedia-w"></option>
<option value="safari" data-icon="fa-safari" data-subtext="safari"></option>
<option value="chrome" data-icon="fa-chrome" data-subtext="chrome"></option>
<option value="firefox" data-icon="fa-firefox" data-subtext="firefox"></option>
<option value="opera" data-icon="fa-opera" data-subtext="opera"></option>
<option value="internet-explorer" data-icon="fa-internet-explorer" data-subtext="internet-explorer"></option>
<option value="tv" data-icon="fa-tv" data-subtext="tv"></option>
<option value="contao" data-icon="fa-contao" data-subtext="contao"></option>
<option value="500px" data-icon="fa-500px" data-subtext="500px"></option>
<option value="amazon" data-icon="fa-amazon" data-subtext="amazon"></option>
<option value="calendar-plus-o" data-icon="fa-calendar-plus-o" data-subtext="calendar-plus-o"></option>
<option value="calendar-minus-o" data-icon="fa-calendar-minus-o" data-subtext="calendar-minus-o"></option>
<option value="calendar-times-o" data-icon="fa-calendar-times-o" data-subtext="calendar-times-o"></option>
<option value="calendar-check-o" data-icon="fa-calendar-check-o" data-subtext="calendar-check-o"></option>
<option value="industry" data-icon="fa-industry" data-subtext="industry"></option>
<option value="map-pin" data-icon="fa-map-pin" data-subtext="map-pin"></option>
<option value="map-signs" data-icon="fa-map-signs" data-subtext="map-signs"></option>
<option value="map-o" data-icon="fa-map-o" data-subtext="map-o"></option>
<option value="map" data-icon="fa-map" data-subtext="map"></option>
<option value="commenting" data-icon="fa-commenting" data-subtext="commenting"></option>
<option value="commenting-o" data-icon="fa-commenting-o" data-subtext="commenting-o"></option>
<option value="houzz" data-icon="fa-houzz" data-subtext="houzz"></option>
<option value="vimeo" data-icon="fa-vimeo" data-subtext="vimeo"></option>
<option value="black-tie" data-icon="fa-black-tie" data-subtext="black-tie"></option>
<option value="fonticons" data-icon="fa-fonticons" data-subtext="fonticons"></option>
